# Generated by Django 3.2.9 on 2021-11-05 20:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=400)),
                ('apellidos', models.CharField(max_length=400)),
            ],
        ),
    ]
