# Generated by Django 3.2.9 on 2021-11-05 20:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=400)),
                ('apellidos', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='recurso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=1000)),
                ('serial', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.marca')),
            ],
        ),
        migrations.CreateModel(
            name='asignacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_desvinculacion', models.DateTimeField(null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.persona')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.recurso')),
            ],
        ),
    ]
