# Generated by Django 3.2.9 on 2021-11-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='asignacion',
            new_name='asignado',
        ),
    ]
