# Generated by Django 3.2.9 on 2021-11-05 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('inventario', '0002_rename_asignacion_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignado',
            name='fecha_desvinculacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignado',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuario.persona'),
        ),
        migrations.DeleteModel(
            name='persona',
        ),
    ]
