# Generated by Django 3.2.9 on 2021-11-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20211105_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='is_asignado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='serial',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
