# Generated by Django 3.2.9 on 2021-11-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20211110_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurso',
            old_name='is_asignado',
            new_name='es_asignado',
        ),
    ]
